pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk add --no-cache maven openjdk8 git curl wget
      - apk --update add tar
      - git clone https://github.com/glyptodon/guacamole-client
      - cd guacamole-client/guacamole-docker/bin
      - ./build-guacamole.sh ../.. .
  
  test:
    image: alpine:3.6
    commands:
      - export GUACD_HOSTNAME=guacd
      - export MYSQL_DATABASE=guacamole_db
      - export MYSQL_USER=guacamole_user
      - export MYSQL_PASSWORD=guacamole_password
      - export MYSQL_HOSTNAME=mysql
      - export GUACD_PORT_4822_TCP_ADDR=guacd
      - export GUACD_PORT_4822_TCP_PORT=4822
      - mkdir -p /opt/guacamole/bin
      - cp guacamole-client/guacamole-docker/bin/start.sh /opt/guacamole/bin/start.sh
      - cp guacamole-client/guacamole.war /opt/guacamole/guacamole.war
      - apk add --no-cache openjdk8 wget 
      - apk --update add tar
      - mkdir -p /usr/local/tomcat/webapps
      - cd /usr/local/tomcat
      - wget http://apache.mirrors.spacedump.net/tomcat/tomcat-9/v9.0.1/bin/apache-tomcat-9.0.1.tar.gz
      - tar xvzf apache-tomcat-9.0.1.tar.gz
      - /opt/guacamole/bin/start.sh