pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk add --no-cache maven openjdk8 git curl
      - apk --update add tar
      - git clone https://github.com/glyptodon/guacamole-client
      - mkdir guacamole-client/out
      - cd guacamole-client/guacamole-docker/bin
      - ./build-guacamole.sh ../.. out
      - ls