pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk add --no-cache maven openjdk8 git
      - git clone https://github.com/glyptodon/guacamole-client
      - mkdir -p out
      - ls
      - ./guacamole-client/guacamole-docker/bin/build-guacamole.sh guacamole-client ${pwd}