pipeline:
  build:
    image: alpine:3.6
    commands:
      - apk add --no-cache maven openjdk8 git curl wget 
      - apk --update add tar
      - wget https://raw.githubusercontent.com/apache/tomcat/50a4a7384e304308f2d4b76fd3d3f41b379e4fb8/bin/catalina.sh
      - git clone https://github.com/glyptodon/guacamole-client
      - cd guacamole-client/guacamole-docker/bin
      - ./build-guacamole.sh ../.. .
  
  test:
    image: alpine:3.6
    commands:
      - export GUACD_HOSTNAME=guacd
      - export MYSQL_DATABASE=guacamole_db
      - export MYSQL_USER=guacamole_user
      - export MYSQL_PASSWORD=guacamole_password
      - export MYSQL_HOSTNAME=mysql
      - export GUACD_PORT_4822_TCP_ADDR=guacd
      - export GUACD_PORT_4822_TCP_PORT=4822
      - mkdir -p /opt/guacamole/bin
      - cp guacamole-client/guacamole-docker/bin/start.sh /opt/guacamole/bin/start.sh
      - cp guacamole-client/guacamole.war /opt/guacamole/guacamole.war
      - apk add --no-cache tomcat-native
      - mkdir -p /usr/local/tomcat/webapps/
      - cp catalina.sh /usr/local/tomcat/catalina.sh
      - /opt/guacamole/bin/start.sh