pipeline:
  prepare:
    image: alpine:3.6
    group: prepare
    commands:
      - apk add --no-cache git
      - git clone https://github.com/glyptodon/guacamole-client

  # build-guacamole:
  #   image: alpine:3.6
  #   group: build
  #   commands:
  #     - apk add --no-cache maven openjdk8 git curl wget
  #     - apk --update add tar
  #     - cd guacamole-client/guacamole-docker/bin
  #     - mkdir -p /out
  #     - ./build-guacamole.sh ../.. /out
  #     - cd ../..
  #     - mv /out .
  #     - ls out
  
  build-init:
    image: alpine:3.6
    group: build
    commands:
      - find . -name *.sql
      - cat create-database.sql > init.sql
      - cat guacamole-client/guacamole-docker/bin/initdb.sh >> init.sql
      - cat init.sql

  # docker-guacamole:
  #   image: plugins/docker
  #   group: docker
  #   repo: lowet84/guacamole
  #   secrets: [ docker_username, docker_password ]
  #   tags: alpine
  #   when:
  #     branch: master

  # docker-init:
  #   image: plugins/docker
  #   group: docker
  #   repo: lowet84/mysql-guacamole-init
  #   secrets: [ docker_username, docker_password ]
  #   tags: alpine
  #   dockerfile: Dockerfile.init
  #   when:
  #     branch: master